apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adminer.fullname" . }}
  labels:
    {{- include "adminer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "adminer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "adminer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          - name: ADMINER_PLUGINS
            value: {{ .Values.config.plugins }}
          - name: ADMINER_DESIGN
            value: {{ .Values.config.design }}
          - name: ADMINER_DEFAULT_SERVER
            value: {{ .Values.config.externalserver }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
